### PR TITLE
revert to shelling out and fix tests

### PR DESCRIPTION
**Pull request by zapnap**

### CODE REVIEW

**Comment by technomancy** [comment]
Thanks! Rebased your changes on top of master and applied them.

**Comment by zapnap** [comment]
Awesome! Worth cutting a new gem release at some point in the near future? We should probably toss together a quickie roadmap at some point too. Definitely a far better approach than what I was doing before, cheers.

**Comment by technomancy** [comment]
The user-visible changes so far seem pretty minor; just better error messages and showing text in the default app. I was thinking we would want to land either manifest autogeneration, release signing, or mixed-source builds for the next release. Those are really the only issues I have for a roadmap right now, other than getting away from shelling out in the build.

**Comment by zapnap** [comment]
Ah I thought the exec strategy might be broken in 0.1, didn't check it. 

Mixed-source builds would be really nice for the next release. Release signing is another critical feature before it can be used for production stuff. Manifest autogeneration would be a nice to have, but personally I would place it at a lower priority.

**Pull request closed without merging**
